### ISSUE TITLE
Break on build. (VRCFury support?)

### ISSUE THREAD

**Issue by u-Kotovsky** [Ess-Ka/EsskaAV3Obfuscator#11]
My avatar uses VRCFury to add such things as clothes, items and so but it seems to be not building VRCFury and then obfuscate the avatar.

**Comment by Ess-Ka** [comment]
Hello
VRCFury is new for me. If it uses additional animators on GameObjects inside the avatar hierarchy, it will not be supported. But I cannot say much about, whitout deeper analysis, what it exactly does and how. I will consider to take a look at it when I work for the next update. But expect it not during this summer.

**Comment by Ess-Ka** [comment]
Sorry for the long time of waiting. I did some research into VRCFury and came to the conclusion that I can't support it.
