### ISSUE TITLE
Obfuscated Meshes are broken

### ISSUE THREAD

**Issue by gonsodany** [Ess-Ka/EsskaAV3Obfuscator#13]
This is what the original mesh looks like
![image](https://github.com/Ess-Ka/EsskaAV3Obfuscator/assets/24687133/5cd7a64c-2d45-4e85-8c3a-7ef113356b9a)

And this is what the obfuscated mesh looks like
![image](https://github.com/Ess-Ka/EsskaAV3Obfuscator/assets/24687133/59b39068-d334-43aa-b1c4-2196507f8841)

Only seems to happen in some meshes but its annoiyng nonetheless never knowing if i'll be able to obfuscate my avatar or not

**Comment by gonsodany** [comment]
If we could please talk about ways that this could be fixed i would appreciate it very much since i've noticed this issue for a few months now

**Comment by gonsodany** [comment]
![image](https://github.com/Ess-Ka/EsskaAV3Obfuscator/assets/24687133/b0894e51-f7e0-4b7a-a32b-67d8ff86e0c8)
![image](https://github.com/Ess-Ka/EsskaAV3Obfuscator/assets/24687133/57d8802f-16ef-457f-9d16-09457007023a)


No idea what causes this but i would really thank you for helping me fix this

**Comment by Ess-Ka** [comment]
Thanks for reporting! Fixed in v2.1.3.
