### ISSUE TITLE
Animated Animator parameteres Obfuscation

### ISSUE THREAD

**Issue by gonsodany** [Ess-Ka/EsskaAV3Obfuscator#4]
![image](https://user-images.githubusercontent.com/24687133/229381614-3fd05001-d5f7-45b7-8e60-c44dc1873e87.png)
i noticed that if you have a controller parameter in any animation that it doesnt obfuscate that so it says the parameter is missing since it got obfuscated in the controller and not in the animation.

**Comment by Ess-Ka** [comment]
Yes - the new package is 2.0.1.

**Comment by gonsodany** [comment]
Works
