### ISSUE TITLE
BlendShape gets obfuscated in animation even when Mesh obfuscation is disabled

### ISSUE THREAD

**Issue by gonsodany** [Ess-Ka/EsskaAV3Obfuscator#5]
When i obfuscated just the parameters and the layers and uncheck the mesh obfuscation option it still obfuscates the blendshapes in the animation, breaking the animations
![image](https://user-images.githubusercontent.com/24687133/230788956-7914dca1-8300-4fa3-a9e6-78db5542207a.png)
![image](https://user-images.githubusercontent.com/24687133/230788971-1106be66-d9b7-4b50-81ec-e6971d015d18.png)
![image](https://user-images.githubusercontent.com/24687133/230788983-e91b7966-0ac5-4619-8b3f-28533dbf7047.png)

**Comment by Ess-Ka** [comment]
Hi
Oh wow! I wonder that no one has remarked this issue before. It happened, when blend shapes was checked, but mesh not. The flag for blend shapes behind was still considered, regardless whats set for the mesh. It's fixed wit 2.0.2. Thanks for reporting!

**Comment by gonsodany** [comment]
Thank you so much for your fast development, i really appreciate it
