### ISSUE TITLE
Obfuscation infinite loop with complex direct blendtrees

### ISSUE THREAD

**Issue by SouljaVR** [Ess-Ka/EsskaAV3Obfuscator#7]
Hi Esska,

Firstly, thank you for such a wonderful tool. I have recently encountered an issue with it that I am able to reproduce. It seems complex direct blendtrees can cause the obfuscation to keep re-obfuscating the FX layer, creating multiple copies in the 'obfuscated' folder and it pretty much never ends. You have to force close unity. I was able to reproduce this by applying a complex VRCFT blendtree to my FX layer with single blend tree enabled + parameter mismatching.

I am specifically using this to create the blendtree setup: https://github.com/rrazgriz/VRCFTGenerator

You can try applying this to any avatar, regardless of whether it has face tracking blendshapes or not. You can follow the full facetracking example to set it up and apply it:

https://github.com/benaclejames/VRCFaceTracking/wiki/Setup-Examples

**Comment by Ess-Ka** [comment]
Hello and thanks for your feedback :-)

I use FaceTracking too, but I made my own generator for it. I have to investigate, what happens here with the blend trees. Currently I am busy with another project. I will inform you, as soon I start with this issue and have some findings.

**Comment by SouljaVR** [comment]
I ended up doing the same and all is well now, thank you!

**Comment by Ess-Ka** [comment]
Best issues are self solving issues! :-D Ok, then I will close it. If it hapens again in future, feel free to open an new one.
