### ISSUE TITLE
Остановка на режиме Obfuscate Controllers + Animation Clips

### ISSUE THREAD

**Issue by Kolaadsd** [Ess-Ka/EsskaAV3Obfuscator#8]
![1Безымянный](https://github.com/Ess-Ka/EsskaAV3Obfuscator/assets/38835695/dadbd138-d211-4104-a3bc-cab13753752f)
![2Безымянный](https://github.com/Ess-Ka/EsskaAV3Obfuscator/assets/38835695/8a635bf8-bcf2-4615-90ad-0825bcdfe74f)
![Безымянный](https://github.com/Ess-Ka/EsskaAV3Obfuscator/assets/38835695/cff6d4dd-3212-4479-83cf-e400ef09a1d7)
Ошибка и потом завис в положении (Obfuscate Controllers + Animation Clips)

**Comment by Ess-Ka** [comment]
Hello and thanks for reporting! This error happened because the source parameter of a parameter driver was null. This should usually not be null, also when the field is empty. I cannot reproduce the error, but will add an additional null check to handle it.

**Comment by Ess-Ka** [comment]
Bug is fixed. Already available within package 2.0.4. Please let me know, if it works for you.

**Comment by Kolaadsd** [comment]
Это сработало и все функции работают как надо)
![image](https://github.com/Ess-Ka/EsskaAV3Obfuscator/assets/38835695/ff49115d-d787-4689-9b60-26cd8488708f)

**Comment by Ess-Ka** [comment]
Depends on what exactly should be ignored. Only the name of the body game object or also mesh/shape keys/related animation/bones/parameters on it? In combination, it can be very complex.

**Comment by Ess-Ka** [comment]
Ok, I understand. MMD animations probably always references a game object called "Body" and will control some standard shape keys to animate the face. So, not only the name of the the game object has to be original. The shape key names has to be original too.

I could add a "MMD safe" checkbox, which would handle this case. All shape keys on the body mesh would not be obfuscated then. I think, this should be user friedly. What do you think?

**Comment by Kolaadsd** [comment]
Yes

**Comment by Ess-Ka** [comment]
I have created a new issue #9 to handle this task. You can add additional comments there. It will take some days until it is available.
