### ISSUE TITLE
Add a checkbox to keep MMD still working

### ISSUE THREAD

**Issue by Ess-Ka** [Ess-Ka/EsskaAV3Obfuscator#9]
The checkbox has to be inactive by default. When activated, the game object called "Body" and the shape keys on it will not be obfuscated. This way, MMD animations should still work.

**Comment by Ess-Ka** [comment]
Added "Preserve MMD" checkbox in version 2.0.5. Tested in two popular MMD worlds.

**Comment by Kolaadsd** [comment]
Nice :3
